import { NextResponse } from 'next/server'

export async function GET() {
  const mock = [
    {
      id: '1',
      userId: 'Olivia',
      roomId: 1,
      message: 'hello',
      type: 'text',
      language: 'eng',
      targetLanguage: 'kor',
      isSafe: true,
      timestamp: 1758198000000,
    },
    {
      id: '2',
      userId: 'Lilly',
      roomId: 1,
      message: 'hello',
      type: 'text',
      language: 'eng',
      targetLanguage: 'kor',
      isSafe: true,
      timestamp: 1758198000000,
    },
    {
      id: '3',
      userId: 'Olivia',
      roomId: 1,
      message: 'nice to meet u',
      type: 'text',
      language: 'eng',
      targetLanguage: 'kor',
      isSafe: true,
      timestamp: 1758198000000,
    },
    {
      id: '4',
      userId: 'Lilly',
      roomId: 1,
      message: 'nice to meet u too',
      type: 'text',
      language: 'eng',
      targetLanguage: 'kor',
      isSafe: true,
      timestamp: 1758198000000,
    },
    {
      id: '5',
      userId: 'Olivia',
      roomId: 1,
      message: 'this is my first time that using this app',
      type: 'text',
      language: 'eng',
      targetLanguage: 'kor',
      isSafe: true,
      timestamp: 1758198000000,
    },
    {
      id: '6',
      userId: 'Olivia',
      roomId: 1,
      message: 'how bout u?',
      type: 'text',
      language: 'eng',
      targetLanguage: 'kor',
      isSafe: true,
      timestamp: 1758198000000,
    },
    {
      id: '7',
      userId: 'Lilly',
      roomId: 1,
      message: 'same here',
      type: 'text',
      language: 'eng',
      targetLanguage: 'kor',
      isSafe: true,
      timestamp: 1758198000000,
    },
  ]
  return NextResponse.json(mock, { status: 200 })
}
